### ISSUE TITLE
Compatibility issue with 5.2.9

### ISSUE THREAD

**Issue by goenner** [SondagesPro/LS-registerQuick#2]
Error Message: Missing configuration file for plugin registerQuick, looked in location /home/www/......./plugins/registerQuick/config.xml

**Comment by Shnoulle** [comment]
Yes, not tested in 5.X currently.

**Comment by Shnoulle** [comment]
Can you report on https://gitlab.com/SondagesPro/SurveyAccess/registerQuick/-/issues 
Maybe you can test with a confix.xml ?
